
- name: "Upload deployment files"
  copy:
    src: "yml/"
    dest: "/tmp/k8s/yml/"
  when: "ansible_ssh_host == groups['k8s-master'][0]"

- name: "Deployment kubernetes monitor system"
  shell: "kubectl --server=http://{{groups['k8s-master'][0]}}:8080 apply -f /tmp/k8s/{{item | regex_replace(role_path + '/files/', '')}}"
  with_items: "{{ lookup('pipe', 'find {{role_path}}/files/yml/ -type f ').split('\n') }}"
  when: "ansible_ssh_host == groups['k8s-master'][0]"
