---

- name: "Upload etcd csrfiles"
  template:
    src: etcd-csr.json.template
    dest: /opt/ssl/etcd-csr.json
  when: "inventory_hostname == groups['masters'][0]"

- name: "Create CA"
  shell: "cfssl gencert -ca=/opt/ssl/ca.pem \
  -ca-key=/opt/ssl/ca-key.pem \
  -config=/opt/ssl/config.json \
  -profile=kubernetes etcd-csr.json | cfssljson -bare etcd"
  args:
    chdir: /opt/ssl/
  delegate_to: "{{ groups['masters'][0] }}"
  when: "inventory_hostname == groups['masters'][0]"


- name: "Upload etcd pem file"
  synchronize: src=/opt/ssl/{{ item }} dest=/etc/kubernetes/ssl/
  with_items:
    - etcd.pem
    - etcd-key.pem
  delegate_to: "{{ groups['masters'][0] }}"

- name: "Chmode etcd key file"
  shell: "chmod 644 /etc/kubernetes/ssl/etcd-key.pem"

- name: "Make sure /var/lib/etcd"
  file: path=/var/lib/etcd state=directory

- name: "Install etcd service"
  template:
    src: etcd.service.template
    dest: /etc/systemd/system/etcd.service
