---

- name: "Make sure /opt/etcd"
  file: path=/opt/etcd state=directory
  when: "'etcd-servers' in group_names"

- name: "Install etcd service"
  template: src=docker-compose.yml.j2 dest=/opt/etcd/docker-compose.yml
  become: yes
  when: "'etcd-servers' in group_names"

- name: "Run etcd container"
  shell: "docker-compose up -d"
  args:
   chdir: /opt/etcd
