---
# This role contains common plays that will run on all nodes, it's aim at install common packages such as: docker, docker-compose

- name: Install prerequisite of docker
  yum: name={{ item.name }} state={{ item.state }}
  with_items:
    - { name: 'iptables', state: 'present' }
    - { name: 'git', state: 'present' }
    - { name: 'systemd', state: 'present'}
  become: yes

- name: Unarchive docker binary to /opt
  unarchive: src=docker-1.12.3.tgz dest=/opt
  become: yes

- name: Move to /usr/bin
  shell: "mv /opt/docker/* /usr/bin/"
  become: yes

- name: Install docker service
  copy: src=docker.service dest=/etc/systemd/system/docker.service owner=root group=root mode=0644
  become: yes

- name: Refresh docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for docker service started
  wait_for: path=/var/run/docker/libcontainerd/docker-containerd.sock
  become: yes

- name: Verify docker installation
  shell: /usr/bin/docker version
  become: yes

- name: be sure docker regsitry host is mapped
  lineinfile:
    dest: /etc/hosts
    line: "{{ docker_registry_host }} go-nexus"
    state: present
